export default `vwos-frontend-react-app/package.json | 114 ++++++++++++++++++++---------------
 1 file changed, 65 insertions(+), 49 deletions(-)

diff --git a/vwos-frontend-react-app/package.json b/vwos-frontend-react-app/package.json
index c13fec3ef..5201256fb 100644
--- a/vwos-frontend-react-app/package.json
+++ b/vwos-frontend-react-app/package.json
@@ -21,104 +21,120 @@
     "build-pkw": "webpack --config ./config/pkw/webpack.config.production.js --optimize-minimize",
     "build-nfz": "webpack --config ./config/nfz/webpack.config.production.js --optimize-minimize",
     "start-pkw": "webpack-dev-server --config=config/pkw/webpack.config.development.js --port 3000 --host 0.0.0.0",
-    "start-nfz": "webpack-dev-server --config=config/nfz/webpack.config.development.js --port 3000 --host 0.0.0.0",
+    "start-nfz": "webpack-dev-server --config=config/nfz/webpack.config.development.js --port 3001 --host 0.0.0.0",
+    "pull-template": "node ./server-scripts/write-template.babel --dev",
     "lint": "eslint src/app --fix",
     "test": "jest",
     "prettier": "prettier --write src/app/**/*.*",
     "csscomb": "csscomb src/app",
-    "storybook": "start-storybook -p 9091"
+    "storybook-pkw": "cross-env STORYBOOK_APP_ENV=pkw start-storybook -p 9091",
+    "storybook-nfz": "cross-env STORYBOOK_APP_ENV=nfz start-storybook -p 9091"
   },
   "devDependencies": {
-    "@storybook/addon-actions": "^4.1.4",
-    "@storybook/addon-info": "^4.1.4",
-    "@storybook/addons": "^4.1.4",
-    "@storybook/react": "^4.1.4",
+    "@babel/cli": "^7.2.3",
+    "@babel/core": "^7.2.2",
+    "@babel/plugin-proposal-class-properties": "^7.2.3",
+    "@babel/plugin-proposal-decorators": "^7.2.3",
+    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
+    "@babel/plugin-proposal-function-sent": "^7.2.0",
+    "@babel/plugin-proposal-numeric-separator": "^7.2.0",
+    "@babel/plugin-proposal-throw-expressions": "^7.2.0",
+    "@babel/plugin-syntax-decorators": "^7.2.0",
+    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
+    "@babel/plugin-transform-destructuring": "^7.2.0",
+    "@babel/plugin-transform-runtime": "^7.2.0",
+    "@babel/preset-env": "^7.2.3",
+    "@babel/preset-react": "^7.0.0",
+    "@hot-loader/react-dom": "^16.9.0-4.12.11",
+    "@storybook/addon-actions": "^5.0.9",
+    "@storybook/addon-knobs": "^5.0.9",
+    "@storybook/addon-links": "^5.0.9",
+    "@storybook/addons": "^5.0.9",
+    "@storybook/react": "^5.0.9",
     "autoprefixer": "8.6.5",
-    "babel-cli": "6.26.0",
-    "babel-eslint": "8.2.6",
-    "babel-jest": "22.4.4",
-    "babel-loader": "7.1.5",
-    "babel-plugin-syntax-decorators": "6.13.0",
-    "babel-plugin-transform-decorators": "6.24.1",
-    "babel-plugin-transform-decorators-legacy": "1.3.5",
-    "babel-plugin-transform-runtime": "6.23.0",
-    "babel-polyfill": "6.26.0",
-    "babel-preset-env": "1.7.0",
-    "babel-preset-react": "6.24.1",
-    "babel-preset-react-native": "4.0.1",
-    "babel-preset-stage-2": "6.24.1",
-    "clean-css-brunch": "2.0.0",
+    "babel-core": "^7.0.0-bridge.0",
+    "babel-eslint": "^10.0.1",
+    "babel-jest": "^24.8.0",
+    "babel-loader": "^8.0.5",
+    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
+    "babel-polyfill": "^6.26.0",
+    "change-case": "^3.1.0",
     "clean-webpack-plugin": "0.1.19",
     "copy-webpack-plugin": "4.5.1",
-    "copyfilemon-brunch": "3.3.0",
-    "css-brunch": "2.6.1",
-    "css-loader": "0.28.11",
+    "core-js": "^3.1.3",
+    "cross-env": "^5.2.0",
+    "css-loader": "^2.1.0",
     "csscomb": "4.2.0",
+    "dotenv": "^7.0.0",
     "dotenv-webpack": "1.5.7",
-    "enzyme": "3.6.0",
-    "enzyme-adapter-react-16": "1.5.0",
+    "enzyme": "^3.8.0",
+    "enzyme-adapter-react-16": "^1.7.1",
     "eslint": "5.6.0",
-    "eslint-config-airbnb": "17.0.0",
     "eslint-loader": "2.1.1",
-    "eslint-plugin-import": "2.14.0",
+    "eslint-plugin-import": "^2.14.0",
     "eslint-plugin-jsx-a11y": "6.1.1",
     "eslint-plugin-prettier": "2.6.2",
     "eslint-plugin-react": "7.11.1",
-    "extract-text-webpack-plugin": "4.0.0-beta.0",
     "file-loader": "1.1.11",
     "html-webpack-plugin": "^3.2.0",
     "husky": "0.14.3",
     "ignore-loader": "0.1.2",
-    "javascript-brunch": "2.0.0",
-    "jest": "22.4.3",
-    "jest-fetch-mock": "^1.6.6",
+    "jest": "^24.8.0",
+    "jest-fetch-mock": "^2.1.0",
     "json-schema-faker": "0.5.0-rc15",
     "json-server": "0.14.0",
-    "lint-staged": "^8.0.4",
+    "lint-staged": "^8.1.6",
+    "mini-css-extract-plugin": "0.8.0",
     "node-fetch": "2.2.0",
-    "node-sass": "4.9.3",
+    "node-sass": "^4.12.0",
     "npm-run-all": "4.1.2",
     "optimist": "0.6.1",
     "postcss-loader": "2.1.6",
     "prettier": "1.14.3",
     "prop-types": "15.6.2",
     "raw-loader": "0.5.1",
-    "react-hot-loader": "4.3.11",
+    "react-hot-loader": "4.11.0",
     "redux-devtools-extension": "2.13.5",
     "redux-logger": "3.0.6",
+    "regenerator-runtime": "^0.13.1",
     "sass-loader": "7.1.0",
     "storybook-addon-specifications": "2.1.2",
-    "storybook-readme": "3.3.0",
+    "storybook-readme": "^5.0.8",
     "style-loader": "0.21.0",
-    "stylelint": "9.5.0",
+    "stylelint": "^10.1.0",
     "stylelint-config-recommended-scss": "3.2.0",
     "stylelint-config-standard": "18.2.0",
     "stylelint-scss": "3.3.1",
     "uglifyjs-webpack-plugin": "1.3.0",
-    "webpack": "4.20.0",
+    "url-loader": "1.1.2",
+    "webpack": "^4.35.2",
+    "webpack-bundle-analyzer": "^3.5.0",
     "webpack-cli": "3.1.1",
     "webpack-dev-middleware": "3.4.0",
-    "webpack-dev-server": "3.1.9",
-    "webpack-manifest-plugin": "2.0.4",
+    "webpack-dev-server": "^3.1.14",
+    "webpack-manifest-plugin": "^2.0.4",
     "webpack-merge": "^4.1.4",
     "webpack-notifier": "1.6.0"
   },
   "dependencies": {
+    "@babel/register": "7.4.4",
+    "atob": "^2.1.2",
     "bodymovin": "4.13.0",
+    "btoa": "^1.2.1",
     "classnames": "2.2.6",
     "history": "4.7.2",
     "isomorphic-fetch": "2.2.1",
-    "jwt-decode": "^2.2.0",
-    "lodash": "4.17.11",
+    "jwt-decode": "2.2.0",
+    "lodash": "^4.17.14",
     "moment": "2.22.1",
     "numeral": "2.0.6",
-    "query-string": "^6.2.0",
-    "react": "^16.6.3",
-    "react-click-outside": "^3.0.1",
-    "react-custom-scroll": "^4.0.0",
-    "react-datepicker": "1.6.0",
-    "react-dom": "^16.6.3",
-    "react-redux": "5.0.7",
+    "react": "16.8.6",
+    "react-click-outside": "3.0.1",
+    "react-custom-scroll": "4.0.1",
+    "react-datepicker": "1.8.0",
+    "react-dom": "16.8.6",
+    "react-lottie": "^1.2.3",
+    "react-redux": "6.0.1",
     "react-responsive-carousel": "3.1.42",
     "react-router": "4.3.1",
     "react-router-dom": "4.3.1",
@@ -126,7 +142,7 @@
     "react-scroll": "1.7.10",
     "react-transition-group": "2.4.0",
     "redux": "4.0.0",
-    "redux-form": "7.4.2",
+    "redux-form": "8.2.3",
     "redux-thunk": "2.3.0",
     "uuid": "3.3.2"
   }
`